import { describe, expect, it } from "vitest";
import { needsPlacement, placementMessage } from "@/lib/placement-message";

const problem = (reason: Parameters<typeof placementMessage>[0]["reason"], detail = "", places: unknown[] | null = null) => ({ reason, detail, places });

describe("what a card says when its change has no place", () => {
  it("says the wording wasn't found", () => {
    expect(placementMessage(problem("not_located"), null)).toBe(
      "This wording isn't in the contract as quoted, so the change has no place in the Word file yet."
    );
  });

  it("says how many times the wording was found", () => {
    expect(placementMessage(problem("ambiguous_quote", "", [1, 2, 3]), null)).toMatch(/^This wording appears 3 times/);
  });

  it("names the other change in an overlap", () => {
    expect(placementMessage(problem("overlaps_another_change"), "Attrition measured cumulatively")).toBe(
      "This change and “Attrition measured cumulatively” cover the same words. Only one of them can go into the Word file."
    );
    expect(placementMessage(problem("overlaps_another_change"), null)).toMatch(/^This change covers the same words as another one/);
  });

  it("uses the engine's own sentence for the rest", () => {
    expect(placementMessage(problem("in_field", "The wording is generated by a field code, not stored as text."), null)).toBe(
      "The wording is generated by a field code, not stored as text. Word won't let that part of the file be changed."
    );
    expect(placementMessage(problem("crosses_boundary", "The change covers 3 cells but the proposed wording has 1 part."), null)).toMatch(
      /^The change covers 3 cells .* So this change has no place in the Word file as it is written\.$/
    );
  });

  it.each(["raise", "another way", "export"])("never tells the associate to %s", (phrase) => {
    for (const reason of ["not_located", "ambiguous_quote", "overlaps_another_change", "in_field", "crosses_boundary"] as const) {
      expect(placementMessage(problem(reason, "Detail."), null).toLowerCase()).not.toContain(phrase);
    }
  });
});

describe("which problems need a place found", () => {
  it("leaves a blank and a missing wording to their own controls", () => {
    expect(needsPlacement(problem("unfilled_blank"))).toBe(false);
    expect(needsPlacement(problem("no_wording"))).toBe(false);
  });

  it("takes every other reason, and nothing when the change has its place", () => {
    expect(needsPlacement(problem("not_located"))).toBe(true);
    expect(needsPlacement(problem(null))).toBe(false);
    expect(needsPlacement(null)).toBe(false);
  });
});
