/**
 * Types for the export validation oracle (MASTER_PLAN.md §1.6).
 *
 * `RedlineEngineResult` is the contract between a revision engine and this
 * module. The legacy engine satisfies it today; §1.5's replacement satisfies
 * the same one. The oracle never reaches into either engine's internals — it
 * validates an input/output byte pair plus a declaration of which revisions the
 * engine wrote.
 */

/** Why a finding never made it into the document. Closed set so §1.6.5's weekly review can group by cause. */
export type UnappliedReason =
  | "missing_clause"
  | "not_located"
  | "ambiguous_quote"
  | "crosses_boundary"
  | "spans_non_text_content"
  | "overlaps_another_change"
  | "in_content_control"
  | "in_field"
  | "in_header_footer";

export interface UnappliedFinding {
  clause_type: string;
  severity: string;
  quoted_text: string | null;
  reason: UnappliedReason;
}

/** Plain-language text for the associate, shown before download (§1.6.4 Partial). */
export const UNAPPLIED_REASON_TEXT: Record<UnappliedReason, string> = {
  missing_clause: "Not in the contract — added to the appendix at the end instead.",
  not_located: "The quoted wording could not be found in the document.",
  ambiguous_quote:
    "The quoted wording appears in more than one clause and nothing in the finding says which one is meant.",
  crosses_boundary:
    "The wording runs across a table cell, a content control, or the property's own tracked change, which cannot be marked up safely.",
  spans_non_text_content:
    "The wording spans a tab, a line break, or a footnote marker, which the markup cannot carry across.",
  overlaps_another_change: "Another finding already marks up overlapping wording.",
  in_content_control: "The wording sits inside a locked content control.",
  in_field: "The wording is generated by a field code, not stored as text.",
  in_header_footer: "The wording is in a header or footer, which is not marked up.",
};

/** What every revision engine hands the oracle. */
export interface RedlineEngineResult {
  docxBytes: Uint8Array;
  appliedCount: number;
  unapplied: UnappliedFinding[];
  /**
   * The `w:id` values this run wrote. The oracle attributes revisions by this
   * set rather than by author name, so an export stays verifiable when the
   * property's own counsel shares a name with the associate.
   */
  ownRevisionIds: string[];
}

export type CheckName =
  | "archive_readable"
  | "parts_parse"
  | "parts_preserved"
  | "content_types_consistent"
  | "relationships_resolve"
  | "revision_ids_unique"
  | "revision_marks_wellformed"
  | "table_structure_preserved"
  | "paragraph_count_preserved"
  | "reject_round_trip";

export interface CheckResult {
  name: CheckName;
  passed: boolean;
  /** Plain language, shown to the associate when it is the reason for a fallback. */
  detail: string;
}

export type ExportOutcome = "clean" | "partial" | "fallback";

export interface ValidationReport {
  outcome: ExportOutcome;
  checks: CheckResult[];
  /** First failing check's detail; null unless the outcome is "fallback". */
  fallbackReason: string | null;
  unapplied: UnappliedFinding[];
  appliedCount: number;
}
