import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import JSZip from "jszip";

/**
 * Builds the synthetic DOCX fixtures the revision engine is tested against
 * (MASTER_PLAN.md §1.11). Hand-written OOXML rather than generated by a
 * library, so the fixtures do not inherit the assumptions of whichever library
 * we end up choosing — a fixture produced by the tool under test cannot prove
 * that tool handles real-world documents.
 *
 * No CD client contracts, ever. These are invented hotels and invented numbers.
 */

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>`;

const ROOT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

const DOC_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`;

const STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:pPr><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style>
</w:styles>`;

const W_NS =
  'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" ' +
  'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"';

function esc(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** A plain run. rPr is raw XML so fixtures can carry real mixed formatting. */
function run(text: string, rPr = "") {
  return `<w:r>${rPr}<w:t xml:space="preserve">${esc(text)}</w:t></w:r>`;
}

function para(inner: string, pPr = "") {
  return `<w:p>${pPr}${inner}</w:p>`;
}

function heading(text: string) {
  return para(run(text), `<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>`);
}

/** An insertion already present in the document, attributed to the counterparty. */
function ins(id: number, author: string, date: string, inner: string) {
  return `<w:ins w:id="${id}" w:author="${esc(author)}" w:date="${date}">${inner}</w:ins>`;
}

/** A deletion already present. Note w:delText, not w:t — the distinction the accepted/original views turn on. */
function del(id: number, author: string, date: string, text: string, rPr = "") {
  return `<w:del w:id="${id}" w:author="${esc(author)}" w:date="${date}"><w:r>${rPr}<w:delText xml:space="preserve">${esc(text)}</w:delText></w:r></w:del>`;
}

function table(rows: string[][], opts: { header?: boolean } = {}) {
  const grid = `<w:tblGrid>${rows[0].map(() => `<w:gridCol w:w="3000"/>`).join("")}</w:tblGrid>`;
  const body = rows
    .map((cells, r) =>
      `<w:tr>${cells
        .map((c) => {
          const bold = opts.header && r === 0 ? "<w:rPr><w:b/></w:rPr>" : "";
          return `<w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/></w:tcPr>${para(run(c, bold))}</w:tc>`;
        })
        .join("")}</w:tr>`
    )
    .join("");
  return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="single" w:sz="4"/><w:left w:val="single" w:sz="4"/><w:bottom w:val="single" w:sz="4"/><w:right w:val="single" w:sz="4"/><w:insideH w:val="single" w:sz="4"/><w:insideV w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>${grid}${body}</w:tbl>`;
}

function document(bodyXml: string, sectPrExtra = "") {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document ${W_NS}><w:body>${bodyXml}<w:sectPr>${sectPrExtra}<w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`;
}

// Fixed timestamp so regenerating the fixtures produces byte-identical files.
// This is a per-entry option, not a generateAsync one — passing it to
// generateAsync type-checks as an error and silently does nothing, which would
// leave every fixture carrying its own build time and make §1.4.8's
// determinism test fail for reasons that have nothing to do with extraction.
const FIXED_DATE = new Date("2026-01-01T00:00:00Z");

interface ExtraParts {
  contentTypes?: string;
  docRels?: string;
  files?: Record<string, string>;
  sectPrExtra?: string;
}

async function writeDocx(name: string, bodyXml: string, extra: ExtraParts = {}) {
  const zip = new JSZip();
  // createFolders:false is per-entry, not a generateAsync option. Without it
  // JSZip synthesises directory entries (_rels/, word/, word/_rels/) stamped
  // with the current time, ignoring the date below — a regenerated fixture then
  // differed by exactly six bytes, but only when a run crossed a clock second.
  // Real Word documents contain no directory entries anyway.
  const at = { date: FIXED_DATE, createFolders: false };
  zip.file("[Content_Types].xml", extra.contentTypes ?? CONTENT_TYPES, at);
  zip.file("_rels/.rels", ROOT_RELS, at);
  zip.file("word/document.xml", document(bodyXml, extra.sectPrExtra ?? ""), at);
  zip.file("word/_rels/document.xml.rels", extra.docRels ?? DOC_RELS, at);
  zip.file("word/styles.xml", STYLES, at);
  for (const [partPath, content] of Object.entries(extra.files ?? {})) zip.file(partPath, content, at);
  const bytes = await zip.generateAsync({ type: "uint8array" });
  const out = path.join("tests", "fixtures", name);
  await writeFile(out, bytes);
  console.log(`  ${name}  (${bytes.length.toLocaleString()} bytes)`);
}

const COUNTERPARTY = "Dana Reyes";
const CP_DATE = "2026-02-14T10:30:00Z";

// --- Fixture 1: clean simple contract -------------------------------------
const fixture01 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  para(run("This Agreement is entered into between Harborview Grand Hotel (the “Hotel”) and the Client identified below.")),
  heading("1. Room Block"),
  para(run("Client agrees to a room block of three hundred forty (340) rooms at a group rate of $289.00 per night.")),
  heading("2. Attrition"),
  para(run("Attrition shall be measured on a night-by-night basis. Client shall be liable for eighty percent (80%) of the group rate for each unsold room night below ninety percent (90%) of the contracted block.")),
  heading("3. Cancellation"),
  para(run("Cancellation damages shall be calculated as a percentage of total anticipated room revenue.")),
].join("");

// --- Fixture 2: heavy tables ----------------------------------------------
const fixture02 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Cancellation Schedule"),
  para(run("Damages are assessed per the following schedule:")),
  table(
    [
      ["Days Prior to Arrival", "Damages (% of Room Revenue)"],
      ["365 or more", "25%"],
      ["364 to 181", "50%"],
      ["180 to 91", "75%"],
      ["90 to 31", "90%"],
      ["30 or fewer", "100%"],
    ],
    { header: true }
  ),
  heading("2. Attrition Sliding Scale"),
  para(run("Room block attrition is assessed as follows:")),
  table(
    [
      ["Actual Pickup", "Liability"],
      ["90% or greater", "None"],
      ["80% to 89%", "50% of shortfall"],
      ["70% to 79%", "80% of shortfall"],
      ["Below 70%", "100% of shortfall"],
    ],
    { header: true }
  ),
].join("");

// --- Fixture 3: existing tracked changes, one author ----------------------
// The counterparty has already redlined this. Our engine must preserve their
// revisions and attribute ours separately.
const fixture03 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  para(run("This Agreement is entered into between Harborview Grand Hotel and the Client.")),
  heading("1. Attrition"),
  para(
    run("Attrition shall be measured on a ") +
      del(101, COUNTERPARTY, CP_DATE, "cumulative") +
      ins(102, COUNTERPARTY, CP_DATE, run("night-by-night")) +
      run(" basis. Client shall be liable for eighty percent (80%) of the group rate for each unsold room night.")
  ),
  heading("2. Cutoff Date"),
  para(
    run("The room block cutoff date shall be ") +
      ins(103, COUNTERPARTY, CP_DATE, run("thirty (30)")) +
      run(" days prior to arrival.")
  ),
  heading("3. Force Majeure"),
  para(
    run("Neither party shall be liable for failure to perform due to causes beyond its reasonable control") +
      del(104, COUNTERPARTY, CP_DATE, ", including but not limited to acts of God, war, or government action") +
      run(".")
  ),
].join("");

// --- Fixture 4: two authors, overlapping ---------------------------------
// The hard case: our deletion will need to nest inside an existing w:ins from
// a different author (§1.5.7), which is the case most likely to corrupt a file.
const AUTHOR_B = "Morgan Ellis";
const B_DATE = "2026-03-02T16:45:00Z";
const fixture04 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Attrition"),
  para(
    run("Attrition is measured ") +
      ins(201, COUNTERPARTY, CP_DATE, run("night-by-night at ninety percent (90%) of the block")) +
      run(", with liability at ") +
      ins(202, AUTHOR_B, B_DATE, run("one hundred percent (100%)")) +
      del(203, COUNTERPARTY, CP_DATE, "eighty percent (80%)") +
      run(" of the group rate.")
  ),
  heading("2. Resale"),
  para(
    del(204, AUTHOR_B, B_DATE, "Hotel shall use commercially reasonable efforts to resell unused rooms and credit the proceeds against damages.") +
      ins(205, AUTHOR_B, B_DATE, run("Hotel has no obligation to resell unused rooms."))
  ),
  heading("3. Mixed Formatting"),
  // Bold/italic split across runs inside one sentence — §1.5.4's rPr cloning
  // must survive a span that crosses these boundaries.
  para(
    run("The ") +
      run("total", "<w:rPr><w:b/></w:rPr>") +
      run(" amount due is ") +
      run("$47,500.00", "<w:rPr><w:b/><w:i/></w:rPr>") +
      run(" payable on signing.")
  ),
].join("");

// --- Fixture 6: contract terms in headers and footers ---------------------
// Hotels routinely put the cutoff date and cancellation notice terms in a
// header or footer. The current pipeline never reads those parts, so terms
// living there are invisible to analysis entirely (§1.4.1).
const HEADER_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:hdr ${W_NS}>${para(run("Harborview Grand Hotel - Group Agreement. Room block cutoff: thirty (30) days prior to arrival."))}</w:hdr>`;

const FOOTER_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:ftr ${W_NS}>${para(run("Cancellation notices must be delivered in writing to the Director of Sales. Late notice incurs one hundred percent (100%) of anticipated room revenue."))}</w:ftr>`;

const FIXTURE06_PARTS: ExtraParts = {
  contentTypes: CONTENT_TYPES.replace(
    "</Types>",
    `  <Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/>
  <Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>
</Types>`
  ),
  docRels: DOC_RELS.replace(
    "</Relationships>",
    `  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>
</Relationships>`
  ),
  files: { "word/header1.xml": HEADER_XML, "word/footer1.xml": FOOTER_XML },
  sectPrExtra: `<w:headerReference w:type="default" r:id="rId2"/><w:footerReference w:type="default" r:id="rId3"/>`,
};

const fixture06 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  para(run("The terms set out in the header and footer of this document form part of this Agreement.")),
  heading("1. Room Block"),
  para(run("Client agrees to a room block of two hundred (200) rooms at $329.00 per night.")),
].join("");

// --- Fixture 5: moveFrom / moveTo -----------------------------------------
// Word records a relocated clause as a move pair, not delete+insert. An engine
// that only understands w:ins/w:del sees the moveFrom text as still present in
// the contract, and would analyse a clause that has actually moved elsewhere.
const fixture05 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Deposits"),
  para(
    run("A deposit is due at signing. ") +
      `<w:moveFromRangeStart w:id="300" w:name="move_indemnity"/>` +
      `<w:moveFrom w:id="301" w:author="${COUNTERPARTY}" w:date="${CP_DATE}"><w:r><w:delText xml:space="preserve">Group shall indemnify Hotel against all claims arising from the event.</w:delText></w:r></w:moveFrom>` +
      `<w:moveFromRangeEnd w:id="300"/>`
  ),
  heading("2. Indemnification"),
  para(
    `<w:moveToRangeStart w:id="302" w:name="move_indemnity"/>` +
      `<w:moveTo w:id="303" w:author="${COUNTERPARTY}" w:date="${CP_DATE}"><w:r><w:t xml:space="preserve">Group shall indemnify Hotel against all claims arising from the event.</w:t></w:r></w:moveTo>` +
      `<w:moveToRangeEnd w:id="302"/>` +
      run(" Each party's liability is capped at the total contract value.")
  ),
].join("");

// --- Fixture 7: multi-level numbering and a cross-reference field ----------
const NUMBERING_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:numbering ${W_NS}>
  <w:abstractNum w:abstractNumId="0">
    <w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/></w:lvl>
    <w:lvl w:ilvl="1"><w:start w:val="1"/><w:numFmt w:val="lowerLetter"/><w:lvlText w:val="%1.%2"/></w:lvl>
    <w:lvl w:ilvl="2"><w:start w:val="1"/><w:numFmt w:val="lowerRoman"/><w:lvlText w:val="%1.%2.%3"/></w:lvl>
  </w:abstractNum>
  <w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num>
</w:numbering>`;

function numbered(text: string, level: number) {
  return para(run(text), `<w:pPr><w:numPr><w:ilvl w:val="${level}"/><w:numId w:val="1"/></w:numPr></w:pPr>`);
}

const FIXTURE07_PARTS: ExtraParts = {
  contentTypes: CONTENT_TYPES.replace(
    "</Types>",
    `  <Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>
</Types>`
  ),
  docRels: DOC_RELS.replace(
    "</Relationships>",
    `  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>
</Relationships>`
  ),
  files: { "word/numbering.xml": NUMBERING_XML },
};

const fixture07 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  numbered("Attrition and Cancellation", 0),
  numbered("Attrition is measured cumulatively across the room block.", 1),
  numbered("Liability applies only below seventy percent (70%) pickup.", 2),
  numbered("Resold rooms are credited against any shortfall.", 2),
  numbered("Cancellation damages follow the schedule below.", 1),
  numbered("Force Majeure", 0),
  // "Section 1.a" here is a field RESULT, not literal text. §1.4.7 requires
  // treating field results as non-modifiable, and instrText as invisible.
  para(
    run("The obligations described in ") +
      `<w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText xml:space="preserve"> REF _Ref_attrition \\h </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r>` +
      run("Section 1.a") +
      `<w:r><w:fldChar w:fldCharType="end"/></w:r>` +
      run(" are suspended during a force majeure event.")
  ),
].join("");

// --- Fixture 8: content controls and field codes ---------------------------
// §1.5.3 requires REFUSING to edit spans inside these, so they must first be
// detectable. A content control holding the attrition percentage is the exact
// shape of a clause we would otherwise try to redline.
const fixture08 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  para(
    run("This Agreement is between Harborview Grand Hotel and ") +
      `<w:sdt><w:sdtPr><w:alias w:val="ClientName"/><w:tag w:val="client_name"/><w:id w:val="9001"/><w:text/></w:sdtPr><w:sdtContent><w:r><w:t xml:space="preserve">Acme Association</w:t></w:r></w:sdtContent></w:sdt>` +
      run(" (the Group).")
  ),
  heading("1. Attrition"),
  para(
    run("Group shall be liable for ") +
      `<w:sdt><w:sdtPr><w:alias w:val="AttritionPct"/><w:tag w:val="attrition_pct"/><w:id w:val="9002"/><w:text/></w:sdtPr><w:sdtContent><w:r><w:t xml:space="preserve">eighty percent (80%)</w:t></w:r></w:sdtContent></w:sdt>` +
      run(" of the group rate for unsold rooms.")
  ),
  heading("2. Dates"),
  para(
    run("This agreement was generated on ") +
      `<w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText xml:space="preserve"> DATE \\@ "MMMM d, yyyy" </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r>` +
      run("March 14, 2026") +
      `<w:r><w:fldChar w:fldCharType="end"/></w:r>` +
      run(" and supersedes prior drafts.")
  ),
].join("");

// --- Fixture 9: tracked changes inside table cells -------------------------
// The cancellation schedule carries the largest dollar exposure in the
// contract and it is a table. Revisions inside cells are a distinct case from
// revisions in body paragraphs, and §1.5.3 blocks spans crossing cell
// boundaries — so the engine has to tell the two apart.
function trackedCell(before: string, after: string, id: number) {
  return (
    `<w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/></w:tcPr><w:p>` +
    del(id, COUNTERPARTY, CP_DATE, before) +
    ins(id + 1, COUNTERPARTY, CP_DATE, run(after)) +
    `</w:p></w:tc>`
  );
}

function plainCell(text: string, bold = false) {
  return `<w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/></w:tcPr>${para(
    run(text, bold ? "<w:rPr><w:b/></w:rPr>" : "")
  )}</w:tc>`;
}

const fixture09 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Cancellation Schedule"),
  `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="3000"/><w:gridCol w:w="3000"/></w:tblGrid>` +
    `<w:tr>${plainCell("Days Prior", true)}${plainCell("Damages", true)}</w:tr>` +
    `<w:tr>${plainCell("180 to 91")}${trackedCell("fifty percent (50%)", "seventy-five percent (75%)", 401)}</w:tr>` +
    `<w:tr>${plainCell("90 to 31")}${trackedCell("seventy-five percent (75%)", "ninety percent (90%)", 403)}</w:tr>` +
    `</w:tbl>`,
  para(run("Damages are calculated on anticipated room revenue.")),
].join("");

// --- Fixture 10: realistic Word run splitting ------------------------------
// What Word actually emits. Editing sessions and the spell checker shatter a
// phrase across runs mid-word, with rsid attributes, proofErr elements and
// bookmarks interleaved. A quoted phrase is almost never one contiguous run,
// which is precisely what §1.5.1 and §1.5.4 have to cope with.
const fixture10 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Attrition"),
  para(
    `<w:r w:rsidR="00A12B34"><w:t xml:space="preserve">Client shall be liable for eighty per</w:t></w:r>` +
      `<w:proofErr w:type="spellStart"/>` +
      `<w:r w:rsidR="00A12B34"><w:t>cent</w:t></w:r>` +
      `<w:proofErr w:type="spellEnd"/>` +
      `<w:r w:rsidR="00B57C11"><w:t xml:space="preserve"> (80</w:t></w:r>` +
      `<w:r w:rsidR="00B57C11"><w:t xml:space="preserve">%) of the group rate</w:t></w:r>` +
      `<w:bookmarkStart w:id="500" w:name="_Ref_attrition"/>` +
      `<w:r><w:t xml:space="preserve"> for each unsold room night.</w:t></w:r>` +
      `<w:bookmarkEnd w:id="500"/>`
  ),
  heading("2. Cutoff"),
  para(
    `<w:r><w:t xml:space="preserve">The cutoff date is thir</w:t></w:r><w:r><w:t>ty</w:t></w:r><w:r><w:t xml:space="preserve"> (30) days prior to arrival.</w:t></w:r>`
  ),
].join("");

// --- Fixture 11: the same phrase four times -------------------------------
// The live engine takes the FIRST regex match and stops (findQuoteMatch), so a
// finding about the cancellation clause can silently redline the attrition
// clause instead. The wrong clause is edited and nothing reports it.
const fixture11 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Attrition"),
  para(run("Group shall be liable for eighty percent (80%) of the group rate for unsold rooms.")),
  heading("2. Cancellation"),
  para(run("Cancellation damages are eighty percent (80%) of anticipated room revenue.")),
  heading("3. Food and Beverage"),
  para(run("Any F&B shortfall is billed at eighty percent (80%) of the contracted minimum.")),
  heading("4. No-Show Rooms"),
  para(run("No-show rooms are charged at eighty percent (80%) of the group rate.")),
].join("");

// --- Fixture 12: tabs, breaks, symbols and smart punctuation --------------
// buildRunIndex skips any run without <w:t>, so tab and break runs are
// invisible to its offset arithmetic while still sitting between text runs.
// Curly quotes and non-breaking hyphens also defeat naive matching, and §1.4.6
// exists to normalise exactly these.
const fixture12 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Payment Schedule"),
  para(
    run("Deposit") +
      `<w:r><w:tab/></w:r>` +
      run("25% at signing") +
      `<w:r><w:br/></w:r>` +
      run("Balance") +
      `<w:r><w:tab/></w:r>` +
      run("due 30 days prior")
  ),
  heading("2. Definitions"),
  // Curly quotes, a non-breaking hyphen (U+2011), a soft hyphen (U+00AD) inside
  // "reasonable", and a non-breaking space before the percent sign.
  para(
    run("The “Group” shall mean the party identified above. Rates are non‑commissionable. ") +
      run("Hotel will use rea­sonable efforts to resell. Attrition is measured at 90 % of the block.")
  ),
  heading("3. Symbols"),
  para(run("Deliverables: ☐ signed contract ☐ deposit → confirmation • final rooming list")),
].join("");

// --- Fixture 13: nested tables and merged cells ---------------------------
// §1.5.3 must refuse a span crossing a cell boundary. A nested table inside a
// cell, plus horizontal (gridSpan) and vertical (vMerge) merges, is where a
// naive "find the runs between these offsets" approach quietly spans cells.
const INNER_TABLE =
  `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="1400"/><w:gridCol w:w="1400"/></w:tblGrid>` +
  `<w:tr><w:tc><w:tcPr><w:tcW w:w="1400" w:type="dxa"/></w:tcPr>${para(run("Tier A"))}</w:tc>` +
  `<w:tc><w:tcPr><w:tcW w:w="1400" w:type="dxa"/></w:tcPr>${para(run("fifty percent (50%)"))}</w:tc></w:tr>` +
  `<w:tr><w:tc><w:tcPr><w:tcW w:w="1400" w:type="dxa"/></w:tcPr>${para(run("Tier B"))}</w:tc>` +
  `<w:tc><w:tcPr><w:tcW w:w="1400" w:type="dxa"/></w:tcPr>${para(run("seventy percent (70%)"))}</w:tc></w:tr>` +
  `</w:tbl>`;

const fixture13 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Cancellation Matrix"),
  `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="3000"/><w:gridCol w:w="3000"/></w:tblGrid>` +
    // A header cell spanning both columns.
    `<w:tr><w:tc><w:tcPr><w:tcW w:w="6000" w:type="dxa"/><w:gridSpan w:val="2"/></w:tcPr>${para(
      run("Cancellation Damages", "<w:rPr><w:b/></w:rPr>")
    )}</w:tc></w:tr>` +
    // A vertically merged cell beside a nested table.
    `<w:tr><w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/><w:vMerge w:val="restart"/></w:tcPr>${para(
      run("Group cancels")
    )}</w:tc><w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/></w:tcPr>${INNER_TABLE}${para(run(""))}</w:tc></w:tr>` +
    `<w:tr><w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/><w:vMerge/></w:tcPr>${para(run(""))}</w:tc>` +
    `<w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/></w:tcPr>${para(
      run("Hotel resells and credits proceeds")
    )}</w:tc></w:tr>` +
    `</w:tbl>`,
  para(run("Damages are calculated on anticipated room revenue.")),
].join("");

// --- Fixture 14: existing revision ids, including a very high one ---------
// The live engine picks its next id by scanning EVERY w:id attribute, not just
// revision ids, and Word rejects a document with duplicate revision ids. A
// bookmark id of 999999 sits here to see whether id allocation collides or
// jumps somewhere unusable.
const fixture14 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Attrition"),
  para(
    run("Attrition is measured at ") +
      del(2147483000, COUNTERPARTY, CP_DATE, "ninety percent (90%)") +
      ins(2147483001, COUNTERPARTY, CP_DATE, run("eighty percent (80%)")) +
      run(" of the contracted block.")
  ),
  heading("2. Cutoff"),
  para(
    `<w:bookmarkStart w:id="999999" w:name="_Ref_cutoff"/>` +
      run("The cutoff date is thirty (30) days prior to arrival.") +
      `<w:bookmarkEnd w:id="999999"/>`
  ),
  heading("3. Deposit"),
  para(
    // A comment range whose id deliberately overlaps the revision id space.
    `<w:commentRangeStart w:id="1"/>` +
      run("A deposit of twenty-five percent (25%) is due at signing.") +
      `<w:commentRangeEnd w:id="1"/><w:r><w:commentReference w:id="1"/></w:r>`
  ),
].join("");

// --- Fixture 15: hyperlinks, footnotes, comments and bookmarks ------------
// Real contracts carry all of these across the clauses we want to redline.
// Editing across them must not orphan a reference or drop the relationship.
const FOOTNOTES_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:footnotes ${W_NS}>
  <w:footnote w:type="separator" w:id="-1"><w:p><w:r><w:separator/></w:r></w:p></w:footnote>
  <w:footnote w:type="continuationSeparator" w:id="0"><w:p><w:r><w:continuationSeparator/></w:r></w:p></w:footnote>
  <w:footnote w:id="1">${para(run("Rates exclude applicable state and local occupancy taxes."))}</w:footnote>
</w:footnotes>`;

const COMMENTS_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:comments ${W_NS}>
  <w:comment w:id="1" w:author="${COUNTERPARTY}" w:date="${CP_DATE}" w:initials="DR">${para(
  run("Confirm this matches the signed LOI.")
)}</w:comment>
</w:comments>`;

const FIXTURE15_PARTS: ExtraParts = {
  contentTypes: CONTENT_TYPES.replace(
    "</Types>",
    `  <Override PartName="/word/footnotes.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml"/>
  <Override PartName="/word/comments.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"/>
</Types>`
  ),
  docRels: DOC_RELS.replace(
    "</Relationships>",
    `  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes" Target="footnotes.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="comments.xml"/>
  <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.com/resort-fees" TargetMode="External"/>
</Relationships>`
  ),
  files: { "word/footnotes.xml": FOOTNOTES_XML, "word/comments.xml": COMMENTS_XML },
};

const fixture15 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Resort Fees"),
  para(
    `<w:commentRangeStart w:id="1"/>` +
      run("A mandatory resort fee of thirty-five dollars ($35.00) per room per night applies, as described at ") +
      `<w:hyperlink r:id="rId4"><w:r><w:rPr><w:color w:val="0000FF"/><w:u w:val="single"/></w:rPr><w:t xml:space="preserve">the hotel fee schedule</w:t></w:r></w:hyperlink>` +
      run(".") +
      `<w:r><w:footnoteReference w:id="1"/></w:r>` +
      `<w:commentRangeEnd w:id="1"/><w:r><w:commentReference w:id="1"/></w:r>`
  ),
  heading("2. Attrition"),
  para(
    `<w:bookmarkStart w:id="700" w:name="_Ref_attrition_clause"/>` +
      run("Group is liable for eighty percent (80%) of the group rate for each unsold room night, measured night-by-night.") +
      `<w:bookmarkEnd w:id="700"/>`
  ),
].join("");

async function main() {
  await mkdir(path.join("tests", "fixtures"), { recursive: true });
  console.log("Generating synthetic DOCX fixtures:");
  await writeDocx("01-clean-simple.docx", fixture01);
  await writeDocx("02-heavy-tables.docx", fixture02);
  await writeDocx("03-tracked-one-author.docx", fixture03);
  await writeDocx("04-tracked-two-authors.docx", fixture04);
  await writeDocx("05-move-from-to.docx", fixture05);
  await writeDocx("06-header-footer-terms.docx", fixture06, FIXTURE06_PARTS);
  await writeDocx("07-numbering-crossref.docx", fixture07, FIXTURE07_PARTS);
  await writeDocx("08-content-controls-fields.docx", fixture08);
  await writeDocx("09-tracked-in-tables.docx", fixture09);
  await writeDocx("10-word-run-splitting.docx", fixture10);
  await writeDocx("11-repeated-phrases.docx", fixture11);
  await writeDocx("12-tabs-breaks-symbols.docx", fixture12);
  await writeDocx("13-nested-merged-tables.docx", fixture13);
  await writeDocx("14-revision-id-collisions.docx", fixture14);
  await writeDocx("15-links-footnotes-comments.docx", fixture15, FIXTURE15_PARTS);
  console.log("Done.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
