import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import JSZip from "jszip";

/**
 * Builds the synthetic DOCX fixtures the revision engine is tested against
 * (MASTER_PLAN.md §1.11). Hand-written OOXML rather than generated by a
 * library, so the fixtures do not inherit the assumptions of whichever library
 * we end up choosing — a fixture produced by the tool under test cannot prove
 * that tool handles real-world documents.
 *
 * No CD client contracts, ever. These are invented hotels and invented numbers.
 */

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>`;

const ROOT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

const DOC_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`;

const STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:pPr><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style>
</w:styles>`;

const W_NS = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"';

function esc(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** A plain run. rPr is raw XML so fixtures can carry real mixed formatting. */
function run(text: string, rPr = "") {
  return `<w:r>${rPr}<w:t xml:space="preserve">${esc(text)}</w:t></w:r>`;
}

function para(inner: string, pPr = "") {
  return `<w:p>${pPr}${inner}</w:p>`;
}

function heading(text: string) {
  return para(run(text), `<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>`);
}

/** An insertion already present in the document, attributed to the counterparty. */
function ins(id: number, author: string, date: string, inner: string) {
  return `<w:ins w:id="${id}" w:author="${esc(author)}" w:date="${date}">${inner}</w:ins>`;
}

/** A deletion already present. Note w:delText, not w:t — the distinction the accepted/original views turn on. */
function del(id: number, author: string, date: string, text: string, rPr = "") {
  return `<w:del w:id="${id}" w:author="${esc(author)}" w:date="${date}"><w:r>${rPr}<w:delText xml:space="preserve">${esc(text)}</w:delText></w:r></w:del>`;
}

function table(rows: string[][], opts: { header?: boolean } = {}) {
  const grid = `<w:tblGrid>${rows[0].map(() => `<w:gridCol w:w="3000"/>`).join("")}</w:tblGrid>`;
  const body = rows
    .map((cells, r) =>
      `<w:tr>${cells
        .map((c) => {
          const bold = opts.header && r === 0 ? "<w:rPr><w:b/></w:rPr>" : "";
          return `<w:tc><w:tcPr><w:tcW w:w="3000" w:type="dxa"/></w:tcPr>${para(run(c, bold))}</w:tc>`;
        })
        .join("")}</w:tr>`
    )
    .join("");
  return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="single" w:sz="4"/><w:left w:val="single" w:sz="4"/><w:bottom w:val="single" w:sz="4"/><w:right w:val="single" w:sz="4"/><w:insideH w:val="single" w:sz="4"/><w:insideV w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>${grid}${body}</w:tbl>`;
}

function document(bodyXml: string) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document ${W_NS}><w:body>${bodyXml}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`;
}

async function writeDocx(name: string, bodyXml: string) {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", CONTENT_TYPES);
  zip.file("_rels/.rels", ROOT_RELS);
  zip.file("word/document.xml", document(bodyXml));
  zip.file("word/_rels/document.xml.rels", DOC_RELS);
  zip.file("word/styles.xml", STYLES);
  // Fixed date so fixtures are byte-stable across runs — the determinism test
  // in §1.4.8 compares extraction output, but a churning fixture makes any
  // failure ambiguous.
  const bytes = await zip.generateAsync({
    type: "uint8array",
    date: new Date("2026-01-01T00:00:00Z"),
  });
  const out = path.join("tests", "fixtures", name);
  await writeFile(out, bytes);
  console.log(`  ${name}  (${bytes.length.toLocaleString()} bytes)`);
}

const COUNTERPARTY = "Dana Reyes";
const CP_DATE = "2026-02-14T10:30:00Z";

// --- Fixture 1: clean simple contract -------------------------------------
const fixture01 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  para(run("This Agreement is entered into between Harborview Grand Hotel (the “Hotel”) and the Client identified below.")),
  heading("1. Room Block"),
  para(run("Client agrees to a room block of three hundred forty (340) rooms at a group rate of $289.00 per night.")),
  heading("2. Attrition"),
  para(run("Attrition shall be measured on a night-by-night basis. Client shall be liable for eighty percent (80%) of the group rate for each unsold room night below ninety percent (90%) of the contracted block.")),
  heading("3. Cancellation"),
  para(run("Cancellation damages shall be calculated as a percentage of total anticipated room revenue.")),
].join("");

// --- Fixture 2: heavy tables ----------------------------------------------
const fixture02 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Cancellation Schedule"),
  para(run("Damages are assessed per the following schedule:")),
  table(
    [
      ["Days Prior to Arrival", "Damages (% of Room Revenue)"],
      ["365 or more", "25%"],
      ["364 to 181", "50%"],
      ["180 to 91", "75%"],
      ["90 to 31", "90%"],
      ["30 or fewer", "100%"],
    ],
    { header: true }
  ),
  heading("2. Attrition Sliding Scale"),
  para(run("Room block attrition is assessed as follows:")),
  table(
    [
      ["Actual Pickup", "Liability"],
      ["90% or greater", "None"],
      ["80% to 89%", "50% of shortfall"],
      ["70% to 79%", "80% of shortfall"],
      ["Below 70%", "100% of shortfall"],
    ],
    { header: true }
  ),
].join("");

// --- Fixture 3: existing tracked changes, one author ----------------------
// The counterparty has already redlined this. Our engine must preserve their
// revisions and attribute ours separately.
const fixture03 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  para(run("This Agreement is entered into between Harborview Grand Hotel and the Client.")),
  heading("1. Attrition"),
  para(
    run("Attrition shall be measured on a ") +
      del(101, COUNTERPARTY, CP_DATE, "cumulative") +
      ins(102, COUNTERPARTY, CP_DATE, run("night-by-night")) +
      run(" basis. Client shall be liable for eighty percent (80%) of the group rate for each unsold room night.")
  ),
  heading("2. Cutoff Date"),
  para(
    run("The room block cutoff date shall be ") +
      ins(103, COUNTERPARTY, CP_DATE, run("thirty (30)")) +
      run(" days prior to arrival.")
  ),
  heading("3. Force Majeure"),
  para(
    run("Neither party shall be liable for failure to perform due to causes beyond its reasonable control") +
      del(104, COUNTERPARTY, CP_DATE, ", including but not limited to acts of God, war, or government action") +
      run(".")
  ),
].join("");

// --- Fixture 4: two authors, overlapping ---------------------------------
// The hard case: our deletion will need to nest inside an existing w:ins from
// a different author (§1.5.7), which is the case most likely to corrupt a file.
const AUTHOR_B = "Morgan Ellis";
const B_DATE = "2026-03-02T16:45:00Z";
const fixture04 = [
  heading("HOTEL GROUP SALES AGREEMENT"),
  heading("1. Attrition"),
  para(
    run("Attrition is measured ") +
      ins(201, COUNTERPARTY, CP_DATE, run("night-by-night at ninety percent (90%) of the block")) +
      run(", with liability at ") +
      ins(202, AUTHOR_B, B_DATE, run("one hundred percent (100%)")) +
      del(203, COUNTERPARTY, CP_DATE, "eighty percent (80%)") +
      run(" of the group rate.")
  ),
  heading("2. Resale"),
  para(
    del(204, AUTHOR_B, B_DATE, "Hotel shall use commercially reasonable efforts to resell unused rooms and credit the proceeds against damages.") +
      ins(205, AUTHOR_B, B_DATE, run("Hotel has no obligation to resell unused rooms."))
  ),
  heading("3. Mixed Formatting"),
  // Bold/italic split across runs inside one sentence — §1.5.4's rPr cloning
  // must survive a span that crosses these boundaries.
  para(
    run("The ") +
      run("total", "<w:rPr><w:b/></w:rPr>") +
      run(" amount due is ") +
      run("$47,500.00", "<w:rPr><w:b/><w:i/></w:rPr>") +
      run(" payable on signing.")
  ),
].join("");

async function main() {
  await mkdir(path.join("tests", "fixtures"), { recursive: true });
  console.log("Generating synthetic DOCX fixtures:");
  await writeDocx("01-clean-simple.docx", fixture01);
  await writeDocx("02-heavy-tables.docx", fixture02);
  await writeDocx("03-tracked-one-author.docx", fixture03);
  await writeDocx("04-tracked-two-authors.docx", fixture04);
  console.log("Done.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
