import { isSynthetic, type SourceRef, type WalkResult } from "../docx";
import type { Applicability, LocatedSpan } from "./types";

/**
 * Whether a located span can be edited, and how (MASTER_PLAN.md §1.5.3).
 *
 * Two strategies come out of this, because a table cannot be treated like
 * prose:
 *
 *   in_place           wrap the runs the span covers in a deletion and an
 *                      insertion, leaving everything around them alone
 *   table_replacement  strike the whole table and insert an edited copy
 *
 * The split is the user's decision of 2026-09-07. A change confined to one cell
 * is edited in place, which reads as one figure struck and one inserted. A
 * change spanning cells replaces the table, because splicing across a cell
 * boundary merges cells and leaves the row short of its declared grid — the
 * corruption Stage 0 measured.
 *
 * Whole-table replacement everywhere would show the property an entire
 * cancellation schedule struck through in red to change one number: legible as
 * a diff, poor as a negotiating document.
 */

export type EditStrategy = "in_place" | "table_replacement";

export interface ApplicabilityResult {
  applicability: Applicability;
  /** Plain language, stored in `findings.applicability_detail`. */
  detail: string;
  /** Present only when applicability is "applicable". */
  strategy?: EditStrategy;
  /** Set for table_replacement — which table to replace. */
  tableIndex?: number;
}

const blocked = (applicability: Applicability, detail: string): ApplicabilityResult => ({
  applicability,
  detail,
});

/** The source refs a span covers, skipping structure the extractor invented. */
export function refsInSpan(part: WalkResult, span: LocatedSpan): SourceRef[] {
  const out: SourceRef[] = [];
  for (let i = span.start; i < span.end && i < part.map.length; i++) {
    const entry = part.map[i];
    if (!isSynthetic(entry)) out.push(entry);
  }
  return out;
}

export function assessApplicability(part: WalkResult, span: LocatedSpan): ApplicabilityResult {
  const refs = refsInSpan(part, span);
  if (refs.length === 0) {
    return blocked("blocked_cross_paragraph", "The quoted wording is document structure, not editable text.");
  }

  // Locked constructs first. Word owns the text inside these, so an edit either
  // will not stick or breaks the control.
  if (refs.some((r) => r.insideContentControl)) {
    return blocked("blocked_content_control", "The wording sits inside a locked content control.");
  }
  if (refs.some((r) => r.insideField)) {
    return blocked("blocked_field", "The wording is generated by a field code, not stored as text.");
  }

  // Tables are decided before paragraphs. Two cells are always two paragraphs,
  // so checking paragraphs first would reject every cross-cell change as a
  // paragraph problem and the table strategy would never run.
  const tables = new Set(refs.map((r) => r.tableIndex));
  const cells = new Set(refs.map((r) => r.cellIndex));

  // More than one value means the span leaves its table — either into the text
  // around it or into a nested one. Neither can be marked up as one change.
  if (tables.size > 1) {
    return blocked(
      "blocked_table",
      "The wording runs across a table boundary, which cannot be marked up as one change."
    );
  }

  const tableIndex = [...tables][0];
  if (tableIndex !== null) {
    if (cells.size > 1) {
      return {
        applicability: "applicable",
        detail: "The wording spans several cells, so the whole table is replaced as a tracked change.",
        strategy: "table_replacement",
        tableIndex,
      };
    }
    // One cell behaves like ordinary prose from here on.
  }

  const paragraphs = new Set(refs.map((r) => r.paragraphIndex));
  if (paragraphs.size > 1) {
    return blocked(
      "blocked_cross_paragraph",
      "The wording runs across a paragraph break, which cannot be marked up as one change."
    );
  }

  return { applicability: "applicable", detail: "Editable in place.", strategy: "in_place" };
}
