import { isSynthetic, type SourceRef, type WalkResult } from "../docx";
import type { Applicability, LocatedSpan } from "./types";
import type { UnappliedReason } from "../redline-validation/types";

/**
 * Whether a located span can be edited, and how (MASTER_PLAN.md §1.5.3).
 *
 * Three strategies come out of this, because one tracked change cannot cross
 * a paragraph break or a cell boundary:
 *
 *   in_place       wrap the runs the span covers in a deletion and an
 *                  insertion, leaving everything around them alone
 *   per_paragraph  the span covers several paragraphs, in the body or inside
 *                  one table cell, so each paragraph takes its own in-place
 *                  change
 *   across_cells   the span covers several cells of a table, so each cell
 *                  takes its own in-place change
 *
 * A change across cells is made cell by cell (the user's decision of
 * 2026-10-08), which reads as one figure struck and one inserted. One change
 * spliced across a cell boundary would merge cells and leave the row short of
 * its declared grid, the corruption Stage 0 measured. When a change can't be
 * placed cell by cell, the engine strikes the table and inserts an edited copy.
 */

export type EditStrategy = "in_place" | "per_paragraph" | "across_cells";

/** The verdicts that come from where the wording sits. `blocked_wording` comes from the wording itself. */
type SpanApplicability = Exclude<Applicability, "blocked_wording">;

export interface ApplicabilityResult {
  applicability: SpanApplicability;
  /** Plain language, stored in `findings.applicability_detail`. */
  detail: string;
  /** What the associate is told, where the verdict alone doesn't say it. */
  reason?: UnappliedReason;
  /** Present only when applicability is "applicable". */
  strategy?: EditStrategy;
  /** Set for across_cells. The table the cells belong to. */
  tableIndex?: number;
}

const blocked = (applicability: SpanApplicability, detail: string): ApplicabilityResult => ({
  applicability,
  detail,
});

/** The source refs a span covers, skipping structure the extractor invented. */
export function refsInSpan(part: WalkResult, span: LocatedSpan): SourceRef[] {
  const out: SourceRef[] = [];
  for (let i = span.start; i < span.end && i < part.map.length; i++) {
    const entry = part.map[i];
    if (!isSynthetic(entry)) out.push(entry);
  }
  return out;
}

export function assessApplicability(part: WalkResult, span: LocatedSpan): ApplicabilityResult {
  const refs = refsInSpan(part, span);
  if (refs.length === 0) {
    return blocked("blocked_cross_paragraph", "The quoted wording is document structure, not editable text.");
  }

  // Locked constructs first. Word owns the text inside these, so an edit either
  // will not stick or breaks the control.
  if (refs.some((r) => r.insideContentControl)) {
    return blocked("blocked_content_control", "The wording sits inside a locked content control.");
  }
  if (refs.some((r) => r.insideField)) {
    return blocked("blocked_field", "The wording is generated by a field code, not stored as text.");
  }

  // Parts the redline leaves alone. They are stored under the locked verdict,
  // the nearest one the database knows, and told apart by their reason.
  if (refs.some((r) => r.insideTextBox)) {
    return {
      ...blocked("blocked_content_control", "The wording sits in a text box, which the redline doesn't change."),
      reason: "in_unedited_part",
    };
  }
  if (refs.some((r) => r.insideUneditedMarkup)) {
    return {
      ...blocked("blocked_content_control", "The wording sits inside markup the redline doesn't change."),
      reason: "in_unedited_part",
    };
  }

  // Tables are decided before paragraphs. Two cells are always two paragraphs,
  // so checking paragraphs first would reject every cross-cell change as a
  // paragraph problem and the table strategy would never run.
  const tables = new Set(refs.map((r) => r.tableIndex));
  const cells = new Set(refs.map((r) => r.cellIndex));

  // More than one value means the span leaves its table — either into the text
  // around it or into a nested one. Neither can be marked up as one change.
  if (tables.size > 1) {
    return blocked(
      "blocked_table",
      "The wording runs across a table boundary, which cannot be marked up as one change."
    );
  }

  const tableIndex = [...tables][0];
  if (tableIndex !== null) {
    if (cells.size > 1) {
      return {
        applicability: "applicable",
        detail: "The wording spans several cells, so each cell is changed in place.",
        strategy: "across_cells",
        tableIndex,
      };
    }
    // One cell behaves like ordinary prose from here on.
  }

  // Whether the proposal can be laid out paragraph by paragraph is the engine's to find out.
  const paragraphs = new Set(refs.map((r) => r.paragraphIndex));
  if (paragraphs.size > 1) {
    return {
      applicability: "applicable",
      detail: "The wording spans paragraphs, so each paragraph is changed on its own.",
      strategy: "per_paragraph",
    };
  }

  return { applicability: "applicable", detail: "Editable in place.", strategy: "in_place" };
}
